-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Wishes (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_added timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Inventory (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    sid INT NOT NULL REFERENCES Users(id), -- uid of a seller/merchant
    pid INT NOT NULL REFERENCES Products(id),
    quantity INT NOT NULL --available quantity
    PRIMARY KEY(sid, pid)
);
    --oid INT NOT NULL,
    --availability VARCHAR(15) NOT NULL,
    --fulfillment VARCHAR(15), -- can be null if still available (not purchased)
    --time_fulfilled INT timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),  -- can be null if still available
    --CHECK(fulfillment in ('Fulfilled', 'Unfulfilled')),
    --PRIMARY KEY(oid, pid)
    -- think about primary key and time_fulfilled
    -- how does order/purchase id play into this?
    -- is price per item/unit needed here?